config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    resources :team_photos, only: [:index, :create]
    resources :posts, only: [:create, :destroy]
  end

  resources :tournaments, only: [:index, :show, :new, :create]
  resources :meetups, only: [:index]

  resources :users, only: [:show, :create] do
    resources :user_photos, only: [:index, :show, :create, :destroy]
    resources :posts, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post "/meetups/search", to: "meetups#search"
      post "/teams/search", to: "teams#search"
      resources :teams do
        resources :team_photos, only: [:index, :create]
        resources :posts, only: [:create, :destroy]
      end
      resources :tournaments, only: [:index, :show, :new, :create]
      resources :registrations, only: [:create]
      # resources :users, only: [:show]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]

  validates :email, uniqueness: true
  validates :username, uniqueness: true, presence: true

  has_many :teams, through: :registrations
  has_many :registrations, dependent: :destroy

  has_many :teams, foreign_key: :manager_id
  has_many :posts, as: :postable, dependent: :destroy

  # has_many :photos
  # accepts_nested_attributes_for :photos

  mount_uploader :profile_photo, ProfilePhotoUploader
  mount_uploaders :photos, PhotoUploader

  # def will_save_change_to_email?
  #   false
  # end
  #
  # def will_save_change_to_profile_photo?
  #   false
  # end
end

app/controllers/api/v1/users_controller.rb
# class Api::V1::UsersController < ApiController
#    before_action :authenticate_user!, except: [:show]
#
#
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    posts = @user.posts
    @posts = posts.order(created_at: :desc)
    @post = Post.new
    @current_user = current_user
    @teams = []
    @user.registrations.each do |registration|
      @teams << Team.where(id: registration.team_id)
    end
  end

end

app/views/users/show.html.erb
  <div class="row feed-page-row">
    <div class="small-12 medium-3 columns"> <hr/>
      <h6 style="text-align: center"> <strong><%= @user.username.upcase %> </strong> </h6>
        <%- if !@user.profile_photo.file.nil? -%>
          <%= image_tag @user.profile_photo.url, :class=>"user-profile-photo" %>
        <%- else -%>
          <div class="empty-profile-photo"><i class="fa fa-futbol fa-10x"></i></div>
        <%- end -%>
      <hr/>

      <h6 class="myteams"> <strong>MyTeams</strong></h6>
      <div class="user-profile-teams striped-list">
        <% @teams.each do |team| %>
         <li>
            <a href="/teams/<%= team[0].id%>">
              <% if !team[0].profile_photo.nil? %>
                <%=image_tag team[0].profile_photo.thumb.url %>
              <% else %>
                <i class="fa fa-futbol"></i>
              <% end %>
              <%= team[0].name %>
            </a>
          </li>
        <% end %>
      </div><hr/>
      <h6><a href="/users/<%= @user.id %>/user_photos"> <strong>Albums</strong> </a> </h6> <hr/>
      <h6><a href="#"><strong>Trophies</strong></a> </h6> <hr/>
      <h6><a href="#"><strong>Messages</strong></a> </h6> <hr/>
      <h6><a href="#"><strong>SoccerNews</strong></a> </h6> <hr/>
    </div>

    <div class="small-12 medium-6 columns"> <hr/>
      <% if @current_user.id == @user.id %>
        <%= form_for [@current_user, @post], url: user_posts_path(@current_user), method: :post do |f| %>
          <div class="field">
            <%= f.label :body, "ADD Posts", {:style=>"font-weight:bold;font-size:1em;"} %>
            <%= f.text_area :body %>

            <span class="feed-choose-photo">
              <%= f.file_field :photos, multiple: true %>
            </span>

            <span class="feed-submit-photo">
              <%= f.submit "Submit Posts / Photos"%>
            </span>
          </div>
        <% end %><hr>
      <% end %>

      <h4> <strong>NewsFeed</strong> </h4>
        <% @posts.each do |post| %>
          <% if @current_user.id == @user.id %>
            <span class='feed-close-button'><%= link_to "X", user_post_path(@current_user, post.id), :method => :delete, data: { confirm: "Are you sure you want to delete this photo?" } %></span>
          <% end %>
          <% if post.photos.length > 0 %>
            <% post.photos.each do |photo|  %>
              <%= image_tag photo.large.url %>
            <% end %>
          <% end %>
          <% if !post.body.empty? %>
            <i class="fas fa-angle-double-right"></i>&nbsp;&nbsp;<%= post.body %>
          <% end %>
          <div class="row feed-icons">
            <div class="small-2 columns"><a href="#"><i class="far fa-comments fa-lg" style="color: purple;"></i></a></div>
            <div class="small-2 columns"><i class="far fa-thumbs-up fa-lg" style="color: Dodgerblue;"></i></div>
            <div class="small-2 columns"><i class="far fa-grin-hearts fa-lg" style="color: red; background-color:light-yellow;"></i></div>
            <div class="small-4 columns feed-date"><%= post.created_at.strftime("%B %d, %Y") %></div>
          </div><hr>
        <% end %>
    </div>

    <div class="small-12 medium-3 columns"> <hr/>
      <h6> <strong>Tables</strong> </h6>
      <br><br><br><br><br><br><br><br>
      <hr>
    </div>
  </div>