config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    resources :team_photos, only: [:index, :create]
    resources :posts, only: [:create, :destroy]
  end

  resources :tournaments, only: [:index, :show, :new, :create]
  resources :meetups, only: [:index]

  resources :users, only: [:show, :create] do
    resources :user_photos, only: [:index, :show, :create, :destroy]
    resources :posts, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post "/meetups/search", to: "meetups#search"
      post "/teams/search", to: "teams#search"
      resources :teams do
        resources :team_photos, only: [:index, :create]
        resources :posts, only: [:create, :destroy]
      end
      resources :tournaments, only: [:index, :show, :new, :create]
      resources :registrations, only: [:create]
      # resources :users, only: [:show]
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_user

  def index
    @user = current_user
    @photos = current_user.photos
  end

  def show
    @photo = @user.photos[params[:id].to_i]
    @photo_id = params[:id].to_i
  end

  def create
    add_more_photos(photos_params[:photos])
    flash[:error] = "Failed uploading photos" unless @user.save
    redirect_to user_photos_path
    # redirect_to :back
  end

  def destroy
    remove_photo_at_index(params[:id].to_i)
    flash[:error] = "Failed deleting photo" unless @user.save
    redirect_to user_photos_path
  end

  private

  def set_user
    @user = current_user
  end

  def add_more_photos(new_photos)
    photos = @user.photos # copy the old photos
    photos += new_photos # concat old photos with new ones
    @user.photos = photos # assign back
  end

  def remove_photo_at_index(index)
    remain_photos = @user.photos # copy the array
    deleted_photo = remain_photos.delete_at(index) # delete the target image
    deleted_photo.try(:remove!) # delete image from S3
    @user.photos = remain_photos # re-assign back
    @user.remove_photos! if remain_photos.empty?
  end

  def photos_params
    params.require(:user).permit({photos: []})
  end
end

app/views/photos/index.html.erb
<div class="albums">
  <h1>Albums</h1>
  <div class="album-container">
    <%- if @photos.length > 0  -%>
      <% @photos.each_with_index do |photo, index| %>
        <li class="user-photos-index">
          <a href='/users/<%= @user.id %>/photos/<%= index %>'> <%= image_tag photo.small.url, {class: "album-image"}%> </a>
          <!-- <span>
            <%# <%= link_to "Delete", user_photo_path(@user, index), :method => :delete, data: { confirm: "Are you sure you want to delete this photo?" } %> %>
          </span> -->
        </li>
      <% end %>
    <%- end -%>
  </div><br/>

  <%= form_for(@user, url: user_photos_path(@user), method: :post) do |f| %>
    <div class="field">
      <%= f.label :photos, "ADD PHOTOS" %>
      <span class="feed-choose-photo">
        <%= f.file_field :photos, multiple: true %>
      </span>
      <span>
        <%= f.submit "UPLOAD PHOTOS" %>
      </span>
    </div>
  <% end %>
</div>

app/views/photos/show.html.erb
<div class="photo-main">
  <div class="row photo-container">
    <div class="small-12 medium-8 columns">
        <%= image_tag @photo.large.url %>
    </div>
    <div class="medium-4 columns">
      <ul class="striped-list">
        <li>Hello World</li>
        <li>Its Soccer Time</li>
        <li>Indeed it is!</li>
      </ul>
    </div>
  </div>
  <%= link_to user_photo_path(@user, @photo_id), :method => :delete, data: { confirm: "Are you sure you want to delete this photo?" } do %>
    <i class="fas fa-trash-alt fa-lg delete-icon"></i>
  <% end %>
</div>