config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    resources :team_photos, only: [:index, :create]
    resources :posts, only: [:create, :destroy]
  end

  resources :tournaments, only: [:index, :show, :new, :create]
  resources :meetups, only: [:index]

  resources :users, only: [:show, :create] do
    resources :user_photos, only: [:index, :show, :create, :destroy]
    resources :posts, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post "/meetups/search", to: "meetups#search"
      post "/teams/search", to: "teams#search"
      resources :teams do
        resources :team_photos, only: [:index, :create]
        resources :posts, only: [:create, :destroy]
      end
      resources :tournaments, only: [:index, :show, :new, :create]
      resources :registrations, only: [:create]
      # resources :users, only: [:show]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FutHub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav data-sticky-container>
      <div data-sticky data-options="marginTop: 0; stickyOn: small;" style="width:100%">
        <div class="title-bar"  data-responsive-toggle="menu-icon-right" data-hide-for="large">
          <div class="title-bar-left title-bar-title">
            <a href="/" class="futhub-title">futHub</a>
          </div>
          <div class="title-bar-title menu-icon-div" data-toggle="menu-icon-right">
            <% if current_user %>
              <% if !current_user.profile_photo.file.nil? %>
                <a href="#" class="profile-photo-anchor tiny dropdown" style="bottom:0.2em"><%= image_tag current_user.profile_photo.thumb.url, {class: "profile-photo"}%></a>
              <% else %>
                <a href="#" class="menu-icon-div small-profile-icon"  >
                  <i class="fa fa-user fa-lg" ></i>
                </a>
              <% end %>
            <% else %>
              <span> sign-In/Up </span>
            <% end %>
            <button class="menu-icon" type="button" style="bottom:0.2em"></button>
          </div>
        </div>

        <div class="top-bar" id="menu-icon-right" >
          <div class="top-bar-left show-for-large">
            <ul class="menu">
              <li><a href="/" class="futhub-title-large">futHub</a></li>
            </ul>
          </div>
          <div class="top-bar-right">
            <ul class="menu vertical large-horizontal" data-responsive-menu="drilldown large-dropdown">
              <ul class="snip1211 menu">
                <%- if current_user -%>
                  <li><%= link_to 'My Page', user_path(current_user.id) %></li>
                <%- end -%>
                <li><a href="/teams">Local Teams</a></li>
                <li><a href="/tournaments">Tournaments</a></li>
                <!-- <li><a href="#">Fields</a></li> -->
                <li><a><%= link_to 'Search Meetup-Teams', meetups_path %></a></li>
              </ul>

              <li class="dropdown-edit">
                <%- if current_user -%>
                  <%- if !current_user.profile_photo.file.nil? -%>
                    <span href="#" class="profile-photo-anchor show-for-large" style="padding: 0;"><%= image_tag current_user.profile_photo.thumb.url, {class: "profile-photo-large"}%></span>
                    <a href="#" class="profile-photo-anchor hide-for-large"><i class="fa fa-user-edit fa-lg" style="color: #FE5D26;"></i></a>
                  <% else %>
                    <span href="#"><i class="fa fa-user-edit fa-lg show-for-large" style="color: #FE5D26;"></i></span>
                    <a href="#" class="hide-for-large"><i class="fa fa-user-edit fa-lg" style="color: #FE5D26;"></i></a>
                  <% end %>
                  <a class="username show-for-large"><%= current_user.username %></a>
                  <ul class="menu">
                    <li class="edit-signout snip1211"><%= link_to 'Edit', edit_user_registration_path, {class: "edit-sign"} %></li>
                    <li class="edit-signout snip1211"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                  </ul>
                <%- else -%>
                  <a href="#" class="sign-in-up-large" style="color:#FE5D26;">Sign IN/UP</a>
                  <ul class="menu">
                    <li class="edit-signout snip1211" ><%= link_to 'Sign In', new_user_session_path, {class: "edit-sign"} %></li>
                    <li class="edit-signout snip1211"><%= link_to 'Sign Up', new_user_registration_path, {class: "edit-sign"} %></li>
                  </ul>
                <%- end -%>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <%- flash.each do |key, value| -%>
      <div data-closable class="callout text-center flash-alert <%= key == 'notice' ? 'success' : 'alert' %>">
        <%= value %>
        <button class="close" type="button" data-close>
          <span aria-hidden="true" class="cross-button">&CircleTimes;</span>
        </button>
      </div>
    <%- end -%>

    <%= yield %>

    <%= javascript_include_tag 'application' %>

    <%- if Rails.env.development? || Rails.env.test? -%>
      <%= javascript_tag do %>
        window.railsEnv = '<%= Rails.env %>'
      <%- end -%>
    <%- end -%>
    <%= javascript_pack_tag 'application' %>

    <%= yield :extra_footer %>
  </body>
</html>